project:
  type: website

website:
  title: "Street Culture in the Gold Coast"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - new-page.qmd
      - this-is-the-the-page-of-many.qmd
      - about.qmd

format:
  html:
    theme:
      - journal
      - brand
    css: styles.css
    toc: true



